#!/bin/bash

# Install Homebrew dependencies.
if [ "$(uname -s)" = "Darwin" ]; then
  HOMEBREW_NO_AUTO_UPDATE=0 brew install protobuf
fi

# Install protoc go plugin.
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6
