#!/bin/bash

# Install Homebrew dependencies.
if [ "$(uname -s)" = "Darwin" ]; then
    brew update
    brew install protobuf
fi

# Install protoc go plugin.
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6

# Install Python gRPC tools for Python gRPC generation.
pip3 install grpcio-tools
