// Common types used in request and response for the multi-agent API.
edition = "2023";

package warp.multi_agent.v1;

import "google/protobuf/go_features.proto";

option go_package = "github.com/warp/warp-proto-apis/multi_agent/v1";
option features.(pb.go).api_level = API_OPAQUE;

enum DocumentType {
    WARP_DRIVE_WORKFLOW = 0;
    WARP_DRIVE_NOTEBOOK = 1;
    WARP_DRIVE_ENV_VAR = 2;
    MEMORY = 3;
    WARP_DOCUMENTATION = 4;
    WEB_PAGE = 5;
    UNKNOWN = 6;
}

message Citation {
    string document_id = 1;
    DocumentType document_type = 2;
}