edition = "2023";

package warp.fraud_scorer.v1;

import "google/protobuf/go_features.proto";
import "multi_agent/v1/request.proto";

option go_package = "github.com/warp/warp-proto-apis/fraud_scorer/v1";
option features.(pb.go).api_level = API_OPAQUE;

service FraudScorer {
  rpc ScoreUser(ScoreRequest) returns (ScoreResponse);
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
}

message ScoreRequest {
  RequestContext request_context = 1;
}

message RequestContext {
  warp.multi_agent.v1.Request request = 1;
}

message ScoreResponse {
  float fraud_score = 1;
  string model_version = 2;
}

message HealthCheckRequest {}

message HealthCheckResponse {
  ServingStatus status = 1;

  enum ServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
  }
}
